/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#fff8f6',
        'on-background': '#27180f',
        surface: '#fff8f6',
        'surface-dim': '#f1d4c5',
        'surface-bright': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff1eb',
        'surface-container': '#ffeae0',
        'surface-container-high': '#ffe3d4',
        'surface-container-highest': '#faddce',
        'on-surface': '#27180f',
        'on-surface-variant': '#52443c',
        'inverse-surface': '#3e2d23',
        'inverse-on-surface': '#ffede5',
        outline: '#85736b',
        'outline-variant': '#d7c2b9',
        primary: '#89502e',
        'on-primary': '#ffffff',
        'primary-container': '#ffb38a',
        'on-primary-container': '#794323',
        'inverse-primary': '#ffb68f',
        secondary: '#3a6752',
        'on-secondary': '#ffffff',
        'secondary-container': '#bceed3',
        'on-secondary-container': '#406d58',
        tertiary: '#6a5c4e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d3c1b0',
        'on-tertiary-container': '#5c4f42',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdbca',
        'primary-fixed-dim': '#ffb68f',
        'on-primary-fixed': '#331200',
        'on-primary-fixed-variant': '#6d3919',
        'secondary-fixed': '#bceed3',
        'secondary-fixed-dim': '#a0d1b7',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#214f3b',
        cocoa: '#27180f',
        peach: '#ffb38a',
        sage: '#3a6752'
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.5rem',
        'DEFAULT': '1rem',
        'md': '1.5rem',
        'lg': '2rem',
        'xl': '3rem',
      },
      spacing: {
        'unit': '8px',
        'container-margin': '32px',
        'gutter': '24px',
        'section-padding': '80px',
        'stack-lg': '48px',
        'stack-md': '24px',
        'stack-sm': '12px',
      }
    },
  },
  plugins: [],
}
